services:
  redis-test:
    build:
      target: redis_test
    environment:
      - NODE_ENV=development
    init: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PWD}
        target: /app

  test-redis-server:
    # image: valkey/valkey:8
    image: redis:8
    restart: unless-stopped
